apiVersion: v1
data:
  token: {{ .Values.secret.tokenValue }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    version: {{ .Chart.AppVersion }}