replicaCount: 1
autoscaling:
  enabled: false
ingress:
  enabled: false
image:
  registry: "docker.io"
  repository: "mrfwdmail"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.0-c3b9c6d-c20e364"
  os: linux
  arch: amd64
secret:
  name: kbot-secret
  tokenKey: token
  tokenName: TELE_TOKEN
  tokenValue:
env:
  app_url: "http://app.tns.svc.cluster.local"
service:
  port: 80
securityContext:
  privileged: true
