replicaCount: 1
autoscaling:
  enabled: false
ingress:
  enabled: false
image:
  registry: "docker.io"
  repository: "mrfwdmail"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v33-45a3a8e"
  os: linux
  arch: amd64
secret:
  name: kbot-secret
  tokenKey: token
  tokenName: TELE_TOKEN
  tokenValue:
service:
  port: 80
securityContext:
  privileged: true
