# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: mrfwdmail
  repo: kbot
  tag: "v1.1.1-a7979da"
  #arch: amd64

  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
  teleToken: "write your telegram token"
securityContext:
  privileged: true
